### ISSUE TITLE
CSS not showing in peak explorer

### ISSUE THREAD

**Issue by joewandy** [kmcluskey/FlyMet#44]
Getting this on localhost. The CSS doesn't showed up, not sure why?

![image](https://user-images.githubusercontent.com/2523391/94423726-fc950b80-0180-11eb-9465-867ef88cd01d.png)

On the server it seems to work fine http://www.flymet.org/met_explore/peak_explorer/All

**Comment by kmcluskey** [comment]
Typically clearing the django_cache and browser cache solves this - but it happens for this page sporadically - I really don't know why. Any advice appreciated. If you type a number instead of 'All' in the URL it's typically fine.

**Comment by joewandy** [comment]
The problem seems to have fixed itself, i'm not sure why
