### ISSUE TITLE
Missing KEGG compound id for standard compounds

### ISSUE THREAD

**Issue by joewandy** [kmcluskey/FlyMet#49]
This line is pretty awkward: https://github.com/kmcluskey/FlyMet/blob/master/met_explore/compound_selection.py#L483-L486

In particular often `missing_cmpd_dict` is missing the compound name (because it's coded by hand), leading to a KeyError.
```
                    added_id = missing_cmpd_dict[c.cmpd_name]
```

Proposed fix: either we load `missing_cmpd_dict` from a longer list of KEGG names -> IDs, or maybe do an online search for it.

**Comment by joewandy** [comment]
As a temporary fix, we've handled the KeyError here https://github.com/kmcluskey/FlyMet/commit/55573d912144cd539026930b08259272d3b09269.

But it would be better to do some kind of KEGG/HMDB/ChEBI lookup, instead of just skipping over the missing compounds.

**Comment by kmcluskey** [comment]
Chebi lookup is not much good as I think the std_cmpds coming from PiMP appear to have KEGG names. Can we lookup KEGG names and get the ID somehow?

**Comment by kmcluskey** [comment]
This now searches Kegg for a matching ID and issues a warning if one is not found.
bioservices needs to be installed and has been added to the Pipfile.
