### ISSUE TITLE
PALS results are random?

### ISSUE THREAD

**Issue by joewandy** [kmcluskey/FlyMet#87]
@kmcluskey can't seem to reproduce this on mac/linux, but it seems that on windows, the PALS pathway ranking results that I get is different each time the data is initialised? This is despite the random seed already [set in the codes](https://github.com/kmcluskey/FlyMet/blob/1b609010e861d03f7ecf910bf66ba17d8c83c426/met_explore/pathway_analysis.py#L63). To check.

**Comment by RonanDaly** [comment]
What was the resolution on this?

**Comment by joewandy** [comment]
Remember to clear cache ...

**Comment by RonanDaly** [comment]
Lol
